appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: eOJ8tcpEGjHelT6HODwfxByRahFGLYRCDBp/muXhA+LRPPdO9zll044n6InkoTDOrTl7lvJ2SVTiS/JkBt9A/e46lfuyNKVCDk+7reUc62SyHx3hwal6t6xpMxS4W4rCwWSDiH74ird7NsI2QGr3f8ZP5teLf2eTGHO3C3XqBwlk+EIQ05gEuXjKZAZl0xqCqce1DiDLOVZk07irn/6HDz9C1wxosCkzwUGwm9v/MdWXBRNFsfAC71ljLPKUDIPdcelFmlFKYj+Vh23/tVAl+qtj+IgEPQCxVzgvrA3vPLNBkRodvovZUGTZ70CRl2u5zBD4Ea0lJGJTxARjz5LoyBsvhd9fnTzu/p74vmJumPVwALTNkAWlP5UfkumdFg5ChbwcESYzarHMTpfilftXBYAoRm7i3ArHkkeA6++GJrKyKGb8+TpZ+SNeqyWq4etKrOeIYxvPmPP9OCq6NAYI7t3R6AA/Ds3RQ1KUYnMiFC0rrmLddDBfQhQ07AGk9w99npReTX00nd/nmOhRIB+50VbEoT0gbLaeJhchEAFXExH69lvVnz+kw4yH3O+V1ldWBYI+tE7b8WWEkY+gIIQvnmN9/CT35pLEUd1IG2b02G6MW/kTuh9izgoJYdf58L4xtD6L7H1LkUYFj48TbsPz14GqSyykP5yWC4ffTA/hM/E=}
