travis:
  secure:
    BINSTAR_TOKEN: X8osphXxownRtWZ2pGq4UUPCYP9yj9tLfb78y4O+AhiHzlabNGxfZYNUGS/O37ttErMjThOfOeTgV/5zGM8OUqV5Sxv9mQZohlLQ/fdDaTeGBZXxut0nC0bjjo77GPwSe4ETFYyTwIdSY9x8CyOjcJdv/BL2rpzLpf1tRJnWrVnKEbxozsF47Q8/rJiVGfqZ0E2Eyn1B3PPstE0xt8c5xGXE/VM+GJgXa/zdM2nRPUvcO8Z3AVwKOX73kgZOnQSJ4ShVnjyEB/qwZ0T2dLdm5WmnitRW+jmo8CA/5axB4EhuSMGijRsHL/H/4DrShfRWYGeqvVrYBp35KORxSZj7mOBKsvjSgbsipbiCcF0H18/jKuoXjDlXPx0xdoCyn2tFl43NvbR0525MrSTm7bVdM5+fLQjPMJy4TLBn5mJS/4qcKZOujqtNPlTaNdfWDW9su3GNiHDCfxyZ2jNGeBWHPwm3tzGO4AXkOIrymXTjUHg0IPKrNSGsmy+ZKbdPQ2N3zb/j9Evl4LfAHKInk5g1nqrL0RNkaXZ1pp17XwHiE1lH0qCGmbkYjRrwmoxxHw6/8ykR/+njl+Xw1A7FRY/oxKRh76XnactzvRZycam6I7sLg6r15eUZbU4RhWFWIFwjg5imTA4FrM6a/ZQR0Kn4O1QUns1bjAHAkowf0vohAug=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
